version: '3'
services:
  bd-pyspark-jupyter:
    build: ../pyspark-jupyter-lab-old
    image: easewithdata/pyspark-jupyter-lab-old
    container_name: pyspark-jupyter-lab-old
    ports:
        - 8888:8888
        - 4040:4040
    environment:
        JUPYTER_PORT: 8888
        SPARK_UI_PORT: 4040
    volumes:
        - spark_data:/data:rw
  bd-spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    command: ln -s /usr/bin/python3 /usr/local/bin/python
    container_name: bd-spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
        - spark_data:/data:rw
  bd-spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    command: ln -s /usr/bin/python3 /usr/local/bin/python
    container_name: bd-spark-worker-1
    depends_on:
      - bd-spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://bd-spark-master:7077"
    volumes:
        - spark_data:/data:rw
  bd-spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    command: ln -s /usr/bin/python3 /usr/local/bin/python
    container_name: bd-spark-worker-2
    depends_on:
      - bd-spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://bd-spark-master:7077"
    volumes:
        - spark_data:/data:rw
  bd-spark-history-server:
      image: bde2020/spark-history-server:3.3.0-hadoop3.3
      container_name: bd-spark-history-server
      depends_on:
        - bd-spark-master
      ports:
        - "18081:18081"
      volumes:
        - /tmp/spark-events-local:/tmp/spark-events
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
volumes:
  spark_data:
